server:
  port: 8090

spring:
  application:
    name: web-flux-app
  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true