server:
  port: 8080

spring:
  application:
    name: feign-app
  jackson:
    property-naming-strategy: SNAKE_CASE

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

greeting-other:
  ribbon:
    # the eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: web-flux-app